### ISSUE TITLE
Improve explanation

### ISSUE THREAD

**Issue by TrakJohnson** [3D-Circle/in-fold-we-trust#12]
- [x] Explanation for upper bound
  - [x] Formal definition of the 2D HP square lattice
  - [x] Explanation for -

**Comment by Pyxidatol-C** [comment]
what about we just remove 'energy' and -

**Comment by TrakJohnson** [comment]
Yeah whatever lets just remove it. @JingjieYang plz do

**Comment by Pyxidatol-C** [comment]
done

**Comment by Pyxidatol-C** [comment]
not really needed anymore
