### ISSUE TITLE
Make good CSS

### ISSUE THREAD

**Issue by TrakJohnson** [3D-Circle/in-fold-we-trust#5]
doesn't look great right now
![2018-01-02-104136_1280x800_scrot](https://user-images.githubusercontent.com/9513815/34534573-eab29d4a-f0be-11e7-9474-ceecff6fef61.png)

**Comment by TrakJohnson** [comment]
Also fix bonds that aren't aligned properly

**Comment by TrakJohnson** [comment]
State of the CSS right now:
![2018-01-03-194322_1280x800_scrot](https://user-images.githubusercontent.com/9513815/34534448-70b6789a-f0be-11e7-91ac-eb4b2727405c.png)

Any other suggestions are welcome

**Comment by Pyxidatol-C** [comment]
@LlamaChinois your time to shine

**Comment by TrakJohnson** [comment]
**IMPORTANT** Bonds are still misaligned (a few pixels)

**Comment by TrakJohnson** [comment]
I think CSS is enough for beta, closing. We can chose colours and stuff in #8
