### ISSUE TITLE
Make some style choices

### ISSUE THREAD

**Issue by TrakJohnson** [3D-Circle/in-fold-we-trust#8]
Choosing is hard.
  - favicon
  - HP colors for the AA

**Comment by Pyxidatol-C** [comment]
yup designing involves a lot of choosing. 
@LlamaChinois your time to shine again 👍

**Comment by Pyxidatol-C** [comment]
We also need a name / title for the website

**Comment by TrakJohnson** [comment]
We also need to chose whether we pin these center things @LlamaChinois

**Comment by TrakJohnson** [comment]
Yeah you know what stuff is good now whatever.
